# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-28 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0002_auto_20170428_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
